FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", corlib = "*"}

[Project]
Name = "LodePng"
TargetType = "BeefLib"
StartupObject = "LodePng.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/Debug-Win64/lodepng.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/Release-Win64/lodepng.lib"]
